export const VARIABLE_LABELS: Record<string, string> = {
  // Fecha
  FECHA_ACTUAL: 'Fecha actual',
  FECHA_DIA: 'Día',
  FECHA_MES: 'Mes (número)',
  FECHA_MES_NOMBRE: 'Mes (nombre)',
  FECHA_ANIO: 'Año',
  FECHA_LARGA: 'Fecha larga',
  FECHA_HORA: 'Hora',
  // Trámite
  USUARIO_LOGUEADO: 'Usuario logueado',
  ID_TRAMITE: 'ID trámite',
  CODIGO_TRAMITE: 'Código trámite',
  OBSERVACION_TRAMITE: 'Observación',
  NOMBRE_SOLICITANTE: 'Nombre solicitante',
  // Estudiante
  NOMBRE_ESTUDIANTE: 'Nombre estudiante',
  ESTUDIANTE_DNI: 'Cédula estudiante',
  ESTUDIANTE_EMAIL: 'Email estudiante',
  ESTUDIANTE_MOBILE: 'Teléfono estudiante',
  ESTUDIANTE_GENERO: 'Género estudiante',
  ESTUDIANTE_FECHA_NACIMIENTO: 'Fecha nacimiento',
  ESTUDIANTE_EDAD: 'Edad',
  ESTUDIANTE_DIRECCION: 'Dirección estudiante',
  ESTUDIANTE_ZONA_RESIDENCIA: 'Zona de residencia',
  ESTUDIANTE_REPRESENTANTE: 'Representante',
  ESTUDIANTE_REPRESENTANTE_MOBILE: 'Teléfono representante',
  ESTUDIANTE_PADRE_NOMBRE: 'Nombre del padre',
  ESTUDIANTE_PADRE_MOBILE: 'Teléfono del padre',
  ESTUDIANTE_MADRE_NOMBRE: 'Nombre de la madre',
  ESTUDIANTE_MADRE_MOBILE: 'Teléfono de la madre',
  ESTUDIANTE_SITUACION_FAMILIAR: 'Situación familiar',
  ESTUDIANTE_VIVE_CON: 'Vive con',
  // Representante
  REPRESENTANTE_NOMBRE: 'Nombre representante',
  REPRESENTANTE_DNI: 'Cédula representante',
  REPRESENTANTE_EMAIL: 'Email representante',
  REPRESENTANTE_MOBILE: 'Teléfono representante',
  REPRESENTANTE_GENERO: 'Género representante',
  REPRESENTANTE_OCUPACION: 'Ocupación representante',
  REPRESENTANTE_NIVEL_EDUCATIVO: 'Nivel educativo representante',
  REPRESENTANTE_DIRECCION: 'Dirección representante',
  // Curso
  CURSO_NOMBRE: 'Nombre del curso',
  CURSO_NIVEL: 'Nivel',
  CURSO_PARALELO: 'Paralelo',
  CURSO_JORNADA: 'Jornada',
  CURSO_ESPECIALIDAD: 'Especialidad',
  CURSO_SUBNIVEL: 'Subnivel',
  ANIO_LECTIVO: 'Año lectivo',
  CURSO_ESTADO: 'Estado del curso',
  CURSO_TUTOR: 'Tutor',
  CURSO_INSPECTOR: 'Inspector',
  CURSO_PSICOLOGO: 'Psicólogo',
  // Institución
  INSTITUCION_NOMBRE: 'Nombre institución',
  INSTITUCION_AMIE: 'Código AMIE',
  INSTITUCION_DISTRITO: 'Distrito',
  INSTITUCION_PROVINCIA: 'Provincia',
  INSTITUCION_CANTON: 'Cantón',
  INSTITUCION_DIRECCION: 'Dirección institución',
  INSTITUCION_EMAIL: 'Email institución',
  INSTITUCION_CONTACTO: 'Contacto institución',
  INSTITUCION_AUTORIDAD: 'Autoridad',
  INSTITUCION_AUTORIDAD_EMAIL: 'Email autoridad',
  INSTITUCION_PERIODO_LECTIVO: 'Período lectivo',
};

export const VARIABLE_GROUPS: Array<{ label: string; keys: string[] }> = [
  { label: 'Fecha', keys: ['FECHA_ACTUAL', 'FECHA_DIA', 'FECHA_MES', 'FECHA_MES_NOMBRE', 'FECHA_ANIO', 'FECHA_LARGA', 'FECHA_HORA'] },
  { label: 'Trámite', keys: ['USUARIO_LOGUEADO', 'ID_TRAMITE', 'CODIGO_TRAMITE', 'OBSERVACION_TRAMITE', 'NOMBRE_SOLICITANTE'] },
  {
    label: 'Estudiante',
    keys: [
      'NOMBRE_ESTUDIANTE', 'ESTUDIANTE_DNI', 'ESTUDIANTE_EMAIL', 'ESTUDIANTE_MOBILE',
      'ESTUDIANTE_GENERO', 'ESTUDIANTE_FECHA_NACIMIENTO', 'ESTUDIANTE_EDAD',
      'ESTUDIANTE_DIRECCION', 'ESTUDIANTE_ZONA_RESIDENCIA',
      'ESTUDIANTE_REPRESENTANTE', 'ESTUDIANTE_REPRESENTANTE_MOBILE',
      'ESTUDIANTE_PADRE_NOMBRE', 'ESTUDIANTE_PADRE_MOBILE',
      'ESTUDIANTE_MADRE_NOMBRE', 'ESTUDIANTE_MADRE_MOBILE',
      'ESTUDIANTE_SITUACION_FAMILIAR', 'ESTUDIANTE_VIVE_CON',
    ],
  },
  {
    label: 'Representante',
    keys: [
      'REPRESENTANTE_NOMBRE', 'REPRESENTANTE_DNI', 'REPRESENTANTE_EMAIL',
      'REPRESENTANTE_MOBILE', 'REPRESENTANTE_GENERO', 'REPRESENTANTE_OCUPACION',
      'REPRESENTANTE_NIVEL_EDUCATIVO', 'REPRESENTANTE_DIRECCION',
    ],
  },
  {
    label: 'Curso',
    keys: [
      'CURSO_NOMBRE', 'CURSO_NIVEL', 'CURSO_PARALELO', 'CURSO_JORNADA',
      'CURSO_ESPECIALIDAD', 'CURSO_SUBNIVEL', 'ANIO_LECTIVO', 'CURSO_ESTADO',
      'CURSO_TUTOR', 'CURSO_INSPECTOR', 'CURSO_PSICOLOGO',
    ],
  },
  {
    label: 'Institución',
    keys: [
      'INSTITUCION_NOMBRE', 'INSTITUCION_AMIE', 'INSTITUCION_DISTRITO',
      'INSTITUCION_PROVINCIA', 'INSTITUCION_CANTON', 'INSTITUCION_DIRECCION',
      'INSTITUCION_EMAIL', 'INSTITUCION_CONTACTO',
      'INSTITUCION_AUTORIDAD', 'INSTITUCION_AUTORIDAD_EMAIL', 'INSTITUCION_PERIODO_LECTIVO',
    ],
  },
];
